apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: cosmic-hamster-api
spec:
  parameters:
    namespace: guest-cosmic-hamster
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    sqlRef:
      name: cosmic-hamster-sql
      backend: private-cloud
    nosqlRef:
      name: cosmic-hamster-nosql
    objectStorageRefs:
      - name: cosmic-hamster-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
