apiVersion: platform.local.lab/v1alpha1
kind: Spa
metadata:
  name: connections-demo
spec:
  parameters:
    namespace: platform-connections-demo
    image: ghcr.io/cujarrett/platform-connections-demo-spa:sha-3314868f89b764d74886550b47c24af1d42cfff9
    repo: https://github.com/cujarrett/platform-connections-demo
    host: connections.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    replicas: 1
    size: xs
    connectionPosture: enforce
    contentSecurityPolicy: "default-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self';"
    apiProxies:
      - path: /authorized/
        upstream: authorized-api.platform-connections-demo.svc.cluster.local
      - path: /unauthorized/
        upstream: unauthorized-api.platform-connections-demo.svc.cluster.local
