apiVersion: v1
kind: Namespace
metadata:
  name: guest-chrome-hamster
  labels:
    launchpad.local.lab/slot: demo3
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-mirror-writer
  namespace: guest-chrome-hamster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-mirror-writer
subjects:
  - kind: ServiceAccount
    name: secret-mirror-controller
    namespace: secret-mirror-controller
