apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: sump-pump-consumer
  namespace: sump-pump
spec:
  parameters:
    image: ghcr.io/cujarrett/sump-pump-consumer:sha-7b1afd3b508b5bcbc3af2cbbf0c95b39706da3bf
    repo: https://github.com/cujarrett/sump-pump
    port: 8080
    scrapeInterval: "10s"
    subscriptionRef:
      name: sump-pump-monitor
