apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: sump-pump-consumer
spec:
  parameters:
    namespace: sump-pump
    image: ghcr.io/cujarrett/sump-pump-consumer:sha-9ed40701664b481338781c8e912625a8170dacac
    repo: https://github.com/cujarrett/sump-pump-consumer
    port: 8080
    scrapeInterval: "10s"
    connectionPosture: enforce
    subscriptionRef:
      name: sump-pump-monitor
