apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: sump-pump-consumer
  namespace: sump-pump
spec:
  parameters:
    image: ghcr.io/cujarrett/sump-pump-consumer:sha-70f970b9a557738ba9c5b682d5a82976bd550059
    repo: https://github.com/cujarrett/sump-pump-consumer
    port: 8080
    scrapeInterval: "10s"
    subscriptionRef:
      name: sump-pump-monitor
