apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: sump-pump-bridge
spec:
  parameters:
    namespace: sump-pump
    image: ghcr.io/cujarrett/sump-pump-bridge:sha-f245d21e8d4ff5d1941be5ea8b67708fc07ba8ae
    repo: https://github.com/cujarrett/sump-pump-bridge
    port: 8080
    host: sump-pump-bridge.local.lab
    tlsIssuer: local-lab-ca-issuer
    topicRef:
      name: home-appliances
    secretRef:
      name: sump-pump-bridge-config
