apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: my-vinyl-api
  namespace: my-vinyl
spec:
  parameters:
    image: ghcr.io/cujarrett/my-vinyl-api:sha-b6263cc542b18fa0943cfc8e7716e1c84d49c3e2
    repo: https://github.com/cujarrett/my-vinyl-api
    port: 8080
    replicas: 1
    host: my-vinyl-api.local.lab
    tlsIssuer: local-lab-ca-issuer
    secretsFrom: [discogs-credentials]
    cache:
      enabled: true
      backend: private-cloud
    provides:
      - name: collection
        auth: mesh
        allowedCallers:
          - { namespace: my-vinyl, app: my-vinyl }
    consumes:
      - { host: api.discogs.com }
