apiVersion: platform.local.lab/v1alpha1
kind: Spa
metadata:
  name: my-vinyl
  namespace: my-vinyl
spec:
  parameters:
    image: ghcr.io/cujarrett/my-vinyl:sha-452b4edcd2469ece16a75d31e79b0fc6111b8a68
    repo: https://github.com/cujarrett/my-vinyl
    host: myvinyl.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    contentSecurityPolicy: "default-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://i.discogs.com; frame-ancestors 'none'; base-uri 'self';"
    replicas: 1
    size: sm
    apiProxies:
      - path: /api/
        app: my-vinyl-api
