apiVersion: platform.local.lab/v1alpha1
kind: Spa
metadata:
  name: mattjarrett-dev
  namespace: mattjarrett-dev
spec:
  parameters:
    image: ghcr.io/cujarrett/mattjarrett.dev:sha-7e9b8929e3bf3a59d65baf6bd80a9a990412ec0a
    repo: https://github.com/cujarrett/mattjarrett.dev
    host: mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    contentSecurityPolicy: "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self';"
    replicas: 1
    size: sm
