apiVersion: platform.local.lab/v1alpha1
kind: Spa
metadata:
  name: mattjarrett-dev
spec:
  parameters:
    namespace: mattjarrett-dev
    image: ghcr.io/cujarrett/mattjarrett.dev:sha-7b6e67741170d1faf38c7645baeec0f3cd738a60
    repo: https://github.com/cujarrett/mattjarrett.dev
    connectionPosture: enforce
    host: mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    contentSecurityPolicy: "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self';"
    replicas: 1
    size: sm
